#!/usr/bin/env bash

echo -n $'Progress: 1.0%\r' >& 2
echo a
sleep 0.5s
echo -n $'Progress: 10.0%\r' >& 2
sleep 0.2s
echo -n $'Progress: 20.0%\r' >& 2
sleep 0.2s
echo -n $'Progress: 30.0%\r' >& 2
sleep 0.2s
echo -n $'Progress: 40.0%\r' >& 2
sleep 0.2s
echo -n $'Progress: 50.0%\r' >& 2
total=$(($RANDOM%30000))
sl="$( echo "scale=3; 1 / $total" | bc )"
for((i=0;i<total;++i)) do
  echo -n "$i,"
  echo -n "Progress: $(echo "scale=1; 50 + 50 * $i / $total" | bc )%"$'\r' >& 2
  sleep "${sl}s"
done
echo
echo b
echo -n $'Progress: 100.0%' >& 2

(($RANDOM%10!=1))